tasks:

  - name: 0.001_lr_no_freeze_backbone
    git_checkout_target: training_just_rpn
    run: |
      python train.py --num-epochs 50 --batch-size 64 --lr-scheduler-name fixed --lr 0.001 --fast-rcnn-dropout 0.0 --run-name 0.001_lr_no_freeze_backbone --checkpoint-interval 10 --no-freeze-backbone --device 
  
  - name: 0.01_lr_no_freeze_backbone
    git_checkout_target: training_just_rpn
    run: |
      python train.py --num-epochs 50 --batch-size 64 --lr-scheduler-name fixed --lr 0.01 --fast-rcnn-dropout 0.0 --run-name 0.01_lr_no_freeze_backbone --checkpoint-interval 10 --no-freeze-backbone --device cuda

  
  - name: 0.001_lr_freeze_backbone
    git_checkout_target: training_just_rpn
    run: |
      python train.py --num-epochs 50 --batch-size 64 --lr-scheduler-name fixed --lr 0.001 --fast-rcnn-dropout 0.0 --run-name 0.001_lr_freeze_backbone --checkpoint-interval 10 --freeze-backbone --device cuda

  
  - name: 0.01_lr_freeze_backbone
    git_checkout_target: training_just_rpn
    run: |
      python train.py --num-epochs 50 --batch-size 64 --lr-scheduler-name fixed --lr 0.01 --fast-rcnn-dropout 0.0 --run-name 0.01_lr_freeze_backbone --checkpoint-interval 10 --freeze-backbone --device cuda
